//CHATROOM CONSTANTS
export const FETCH_CHATROOM_LIST = 'FETCH_CHATROOM_LIST';

export const CREATE_CHATROOM = 'CREATE_CHATROOM';
export const FETCH_CHATROOM = 'FETCH_CHATROOM';
export const UPDATE_CHATROOM = 'UPDATE_CHATROOM';
export const REMOVE_CHATROOM = 'REMOVE_CHATROOM';

export const SET_MESSAGE = 'SET_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_IMAGE = 'SEND_IMAGE';

export const SET_ROOMNAME = 'SET_ROOMNAME';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const CREATE_CHATROOMUSER = 'CREATE_CHATROOMUSER';
export const REMOVE_CHATROOMUSER = 'REMOVE_CHATROOMUSER';
export const UPDATE_CHATROOMUSER = 'UPDATE_CHATROOMUSER';

export const CREATE_CHATROOMRECORD = 'CREATE_CHATROOMRECORD';
export const REMOVE_CHATROOMRECORD = 'REMOVE_CHATROOMRECORD';
export const UPDATE_CHATROOMRECORD = 'UPDATE_CHATROOMRECORD';

export const BACK_TO_CHAT_LIST = 'BACK_TO_CHAT_LIST';

//MAP CONSTANTS
export const FETCH_ALL_DISTRICTS = 'FETCH_ALL_DISTRICTS';
export const FETCH_ALL_LOCATIONS = 'FETCH_ALL_LOCATIONS';

export const CHANGE_ZOOM_LEVEL = 'CHANGE_ZOOM_LEVEL';

export const FETCH_LOCATION = 'FETCH_LOCATION';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';

export const FETCH_DISTRICT = 'FETCH_DISTRICT';
export const CREATE_DISTRICT = 'CREATE_DISTRICT';
export const UPDATE_DISTRICT = 'UPDATE_DISTRICT';
export const REMOVE_DISTRICT = 'REMOVE_DISTRICT';

export const CREATE_LOCATIONIMAGES = 'CREATE_LOCATIONIMAGES';


//USER CONSTANTS
export const CREATE_USER = 'CREATE_USER';
export const FETCH_ALLUSER = 'FETCH_ALLUSER';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USERLOCATION = 'FETCH_USERLOCATION';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const CREATE_FAVPOST = 'CREATE_FAVPOST';
export const REMOVE_FAVPOST = 'REMOVE_FAVPOST';

export const CREATE_USERLOCATION = 'CREATE_USERLOCATION';
export const REMOVE_USERLOCATION = 'REMOVE_USERLOCATION';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
//POST CONSTANTS
export const CREATE_NEWCATEGORY = 'CREATE_NEWCATEGORY';
export const FETCH_ALLCATEGORY = 'FETCH_ALLCATEGORY';

export const FETCH_ALLPOST = 'FETCH_ALLPOST';

export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_POST = 'FETCH_POST';
export const CREATE_POST = 'CREATE_POST';
export const REMOVE_POST = 'REMOVE_POST';
export const UPDATE_POST = 'UPDATE_POST';

export const CREATE_USERFAVPOST = 'CREATE_USERFAVPOST';
export const REMOVE_USERFAVPOST = 'REMOVE_USERFAVPOST';


export const UPDATE_POSTCATEGORY = 'UPDATE_POSTCATEGORY';
export const REMOVE_POSTCATEGORY = 'REMOVE_POSTCATEGORY';


export const CREATE_POSTIMAGES = 'CREATE_POSTIMAGES';
export const UPDATE_POSTIMAGE = 'UPDATE_POSTIMAGE';
export const REMOVE_POSTIMAGE = 'REMOVE_POSTIMAGE';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';


//IMAGE CONSTANTS
export const FETCH_ALLIMAGE = 'FETCH_ALLIMAGE';
export const FETCH_IMAGE = 'FETCH_IMAGE';

