//CHATROOM CONSTANTS
export const FETCH_ALLCHATROOM = 'FETCH_ALLCHATROOM'

export const CREATE_CHATROOM = 'CREATE_CHATROOM'
export const FETCH_CHATROOM = 'FETCH_CHATROOM'
export const UPDATE_CHATROOM = 'UPDATE_CHATROOM'
export const REMOVE_CHATROOM = 'REMOVE_CHATROOM'

export const CREATE_CHATROOMUSER = 'CREATE_CHATROOMUSER'
export const REMOVE_CHATROOMUSER = 'REMOVE_CHATROOMUSER'
export const UPDATE_CHATROOMUSER = 'UPDATE_CHATROOMUSER'

export const CREATE_CHATROOMRECORD = 'CREATE_CHATROOMRECORD'
export const REMOVE_CHATROOMRECORD = 'REMOVE_CHATROOMRECORD'
export const UPDATE_CHATROOMRECORD = 'UPDATE_CHATROOMRECORD'

//MAP CONSTANTS
export const FETCH_ALLDISTRICT = 'FETCH_ALLDISTRICT'

export const FETCH_DISTRICT = 'FETCH_DISTRICT'
export const CREATE_DISTRICT = 'CREATE_DISTRICT'
export const UPDATE_DISTRICT = 'UPDATE_DISTRICT'
export const REMOVE_DISTRICT = 'REMOVE_DISTRICT'

//USER CONSTANTS
export const CREATE_USER = 'CREATE_USER'
export const FETCH_ALLUSER = 'FETCH_ALLUSER'
export const FETCH_USER = 'FETCH_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const REMOVE_USER = 'REMOVE_USER'


export const CREATE_FAVBLOG = 'CREATE_FAVBLOG'
export const REMOVE_FAVBLOG = 'REMOVE_FAVBLOG'

export const CREATE_USERDISTRICT = 'CREATE_USERDISTRICT'
export const REMOVE_USERDISTRICT = 'REMOVE_USERDISTRICT'

export const CREATE_USERCHAT = 'CREATE_USERCHAT'
export const REMOVE_USERCHAT = 'REMOVE_USERCHAT'
export const CREATE_USERCHATRECORD = 'CREATE_USERCHATRECORD'

//BLOG CONSTANTS
export const CREATE_NEWCATEGORY = 'CREATE_NEWCATEGORY'
export const FETCH_ALLCATEGORY = 'FETCH_ALLCATEGORY'

export const FETCH_ALLBLOG = 'FETCH_ALLBLOG'

export const FETCH_BLOG = 'FETCH_BLOG'
export const CREATE_BLOG = 'CREATE_BLOG'
export const REMOVE_BLOG = 'REMOVE_BLOG'
export const UPDATE_BLOG = 'UPDATE_BLOG'

export const UPDATE_BLOGCATEGORY = 'UPDATE_BLOGCATEGORY'
export const REMOVE_BLOGCATEGORY = 'REMOVE_BLOGCATEGORY'

export const UPDATE_BLOGIMAGE = 'UPDATE_BLOGIMAGE'
export const REMOVE_BLOGIMAGE = 'REMOVE_BLOGIMAGE'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'
